{% set version = "1.0.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-metarnaseq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/metaRNASeq_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/metaRNASeq/metaRNASeq_{{ version }}.tar.gz
  sha256: 9901ea9c3d0d53730586f1c1a0e7fbd55d035ea500ad2a6305ca1d589c6e8431

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('metaRNASeq')"           # [not win]
    - "\"%R%\" -e \"library('metaRNASeq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=metaRNASeq
  license: GPL-2.0-or-later
  summary: Implementation of two p-value combination techniques (inverse normal and Fisher methods). A vignette is provided to explain how to perform a meta-analysis from two independent RNA-seq experiments.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
