travis:
  secure:
    BINSTAR_TOKEN: MmRIc0heGKnvsrPxMciCaJaMYcURBExefJkoXVIUIM0Yu13qKLuIVtnhQLW6N2ZfFXiHxq1Vdg1b26OZe5VkpUiAFLU3lvwCaTDIaK6IUjkFmQ5IBbi7pZIn+M45kxFf5MQvXlLKy325+ca1PATtkXQBJ15/qTDz+2jAVN7/Zs1DcYSsMowXcJGa/dmWjY3ANF1zddXhQG0M86MME6fWO5DS0z2iAFoBz5/hxsxVdKGohglogl4T4zEDWbBwmlpAEYvHPBLAo1ZRRz4B3R65ByoinwCVxGKvus+dGodi4dCOeKBQyzwld/TfKVItqlOnB4K9wpYo284ukoobcw14wMaRni5Y50+BP4ZzGEaXrhHdueIaERvLmUSRHylMpONK5RCLUmD6Z5Rwi5QO6ox37LAu5QWlEvWFeMoXOOqdjSGVgDavZgVtpe7XoP376Tx/rOicgHNXPtmeIsXWBD1cMIOey0bkJxS4HwUfu+tAFZK+M4CBTkTO6iJHP8GImuqL7qhOZBYqnvStLoyN3JjiD888FlqehyvoI79BaUc+MsA/Gvu/qmHopR1lhykVHWaWj6Nozv54gGOK++anEPKbTCVoficOUFU9rSgJZrR+9kkF/i5xurC/vhqi8znWQcdsbLtxKkrAmgpcsEkOPxJeWl2H1lQFE59wzqzKY4ngGT0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
