travis:
  secure:
    BINSTAR_TOKEN: vHSslt9da97kezP8o4F3N7HWkE/Mr1w7I/Fc+A099xev0bd2SWRdvh8ITSDfn66NaJnsCrvaGMLuxZ+N7wngByt/mIeSwqWpqazU1i66JHAlKPiBm4WuVTYkLc1dmtVapi+QHw90Oo7//cjNGB2dAxyDCATukS5u2hXbsYy7k1XWcUyQwMDVhQflPpYWbxD+8Net5LpUaVAj0lNvJ48yMBXMRV5UTFBgJgUPLWOv0EL7nwI6qe9dC2wGn/9np1aNajP4rKvc1DA59TyL4rXVKAyJ2CnEzKe3yiWzkv3unr9qkjgr4QC2Uq4RUbgiNQ25eaixzpS8pb5+UOKznt9ofqkAqXEgnkVZqz8yagAi+KVuT1KjEgh6VlgJl9nEK53kJPunAjTeMtdURkfkVjmzRSvG9m2lALvRBmsY6ndCfFA0d+npy6CpWwQggZRSmAP9WqK0osjKioNoP4RTQyOrr2+clzLiD2iZ6pAPzbv40Tf7a2TEhjR7R6TQ3HsdwP1Qv92BQWBmQW2lX823A0LbSpgx77pW6olqi43CtYKYDJ3c/wsIHuKPhzUkkKYL499MwB+dRIWZa27nC6wAELov/jyg5yaLwbBaLpxOicEYFNaZojG7nsyjn6lVjIrui2vcyqhaXS3D74qDdio32Mx78+rkZEz/RSKjtBmVV1+jt34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
